from pathlib import Path
p=Path(r'D:\AGAM_SITE\build_exact.py')
s=p.read_text(encoding='utf-8')
s=s.replace("('tech.html','AGAM TECH','tech'),('gaming.html','GAMING & CUSTOM','gaming'),('home.html','AGAM HOME','house')","('tech.html','TECH','tech'),('gaming.html','GAMING & CUSTOM','gaming'),('home.html','HOME','house')")
s=s.replace("<a class=\"brand\" href=\"index.html\"><span class=\"mark\"></span><span><strong>AGAM</strong><small>פתרונות חכמים לבית ולעסק</small></span></a>","<a class=\"brand\" href=\"index.html\"><img src=\"assets/agam-logo.svg\" alt=\"AGAM — פתרונות חכמים לבית ולעסק\"></a>")
s=s.replace("<footer class=\"footer\"><div class=\"wrap foot\"><b>AGAM • פתרונות חכמים לבית ולעסק</b>","<footer class=\"footer\"><div class=\"wrap foot\"><img class=\"footer-logo\" src=\"assets/agam-logo.svg\" alt=\"AGAM\">")
s=s.replace('<div class=\"mega\">AGAM</div>','<div class=\"mega brand-mega\"><img src=\"assets/agam-logo.svg\" alt=\"AGAM\"></div>',1)
s=s.replace('<h2>AGAM <span>TECH</span></h2>','<h2 class=\"division-title\"><img src=\"assets/agam-mark.svg\" alt=\"\">AGAM <span>TECH</span></h2>')
s=s.replace('<h2>AGAM <span>GAMING & CUSTOM</span></h2>','<h2 class=\"division-title\"><img src=\"assets/agam-mark.svg\" alt=\"\">AGAM <span>GAMING & CUSTOM</span></h2>')
s=s.replace('<h2>AGAM <span>HOME</span></h2>','<h2 class=\"division-title\"><img src=\"assets/agam-mark.svg\" alt=\"\">AGAM <span>HOME</span></h2>')
s=s.replace('<div class=\"mega\">AGAM <span>TECH</span></div>','<div class=\"mega division-mega\"><img src=\"assets/agam-mark.svg\" alt=\"\"><b>AGAM</b> <span>TECH</span></div>')
s=s.replace('<div class=\"mega\">AGAM <span>GAMING & CUSTOM</span></div>','<div class=\"mega division-mega\"><img src=\"assets/agam-mark.svg\" alt=\"\"><b>AGAM</b> <span>GAMING & CUSTOM</span></div>')
s=s.replace('<div class=\"mega\">AGAM <span>HOME</span></div>','<div class=\"mega division-mega\"><img src=\"assets/agam-mark.svg\" alt=\"\"><b>AGAM</b> <span>HOME</span></div>')
s=s.replace('<div class=\"mega\">אודות <span>AGAM</span></div>','<div class=\"mega about-brand\">אודות <span><img src=\"assets/agam-mark.svg\" alt=\"\">AGAM</span></div>')
s=s.replace('<div class=\"kicker\">AGAM</div>','<div class=\"kicker brand-kicker\"><img src=\"assets/agam-mark.svg\" alt=\"\">AGAM</div>')
p.write_text(s,encoding='utf-8')
print('brandified')