from pathlib import Path
ROOT=Path(r'D:\AGAM_SITE')
PHONE='055-934-4185'; WA='972559344185'
def header(active=''):
    nav=[('index.html','דף הבית','home'),('tech.html','TECH','tech'),('gaming.html','GAMING & CUSTOM','gaming'),('home.html','HOME','house'),('about.html','אודות','about'),('gallery.html','גלריה','gallery'),('contact.html','צור קשר','contact')]
    links=''.join(f'<a class="{"active" if key==active else ""}" href="{url}">{txt}</a>' for url,txt,key in nav)
    return f'''<header class="top"><div class="wrap nav"><a class="brand" href="index.html"><img src="assets/agam-logo.png" alt="AGAM"><small class="brand-tagline">פתרונות חכמים לבית ולעסק</small></a><nav class="menu">{links}</nav><div class="actions"><a class="pill call" href="tel:0559344185">☎ {PHONE}</a><a class="pill wa" href="https://wa.me/{WA}">WhatsApp</a></div><button class="hamb" aria-label="תפריט">☰</button></div></header>'''
def footer():
    return f'''<footer class="footer"><div class="wrap foot"><img class="footer-logo" src="assets/agam-logo.png" alt="AGAM"><span>TECH • GAMING & CUSTOM • HOME</span><span>{PHONE}</span></div></footer><div class="mobilebar"><a class="phone" href="tel:0559344185">☎ חיוג</a><a class="whatsapp" href="https://wa.me/{WA}">WhatsApp • {PHONE}</a></div><script src="app.js"></script>'''
def page(title,body,active=''):
    return f'''<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#ffffff"><meta name="description" content="AGAM פתרונות חכמים לבית ולעסק"><title>{title}</title><link rel="stylesheet" href="styles.css"></head><body>{header(active)}{body}{footer()}</body></html>'''
def service(img,title,text,href='contact.html',custom=False):
    media=f'<div class="logo-glow"><div class="sign">AGAM</div></div>' if custom else f'<img src="{img}" alt="{title}">'
    return f'''<a class="service" href="{href}">{media}<div class="service-body"><h3>{title}</h3><p>{text}</p><span class="service-link">לפרטים ←</span></div></a>'''
home=f'''<section class="hero home-hero"><div class="wrap"><div class="hero-copy"><div class="mega brand-mega"><img src="assets/agam-logo.png" alt="AGAM"><small class="brand-tagline hero-tagline">פתרונות חכמים לבית ולעסק</small></div><h1>כל פתרונות הטכנולוגיה, הגיימינג וההתקנות <span style="color:var(--blue)">לבית ולעסק — במקום אחד.</span></h1><p>שירות מקצועי, עבודה נקייה, מחירים הוגנים וליווי אישי — מהייעוץ ועד ההתקנה.</p></div></div></section><section class="divisions"><div class="wrap"><div class="division-grid"><a class="division" href="tech.html"><img class="division-img" src="assets/camera.jpg"><div class="division-body"><h2 class="division-title"><img src="assets/agam-mark.png" alt="">AGAM <span>TECH</span></h2><p>אינטרנט, רשתות, מצלמות אבטחה, סיבים, טלפוניה ומערכות לעסקים ולמוסדות.</p><span class="btn blue">לפרטים ←</span></div></a><a class="division" href="gaming.html"><img class="division-img" src="assets/gaming.jpg"><div class="division-body"><h2 class="division-title"><img src="assets/agam-mark.png" alt="">AGAM <span>GAMING & CUSTOM</span></h2><p>מחשבי גיימינג, קונסולות, פרספקס, CNC, עיצוב אישי ועמדות בהתאמה אישית.</p><span class="btn blue">לפרטים ←</span></div></a><a class="division" href="home.html"><img class="division-img" src="assets/home.jpg"><div class="division-body"><h2 class="division-title"><img src="assets/agam-mark.png" alt="">AGAM <span>HOME</span></h2><p>תליית טלוויזיות, בית חכם, התקנות, הנדימן ופתרונות לבית.</p><span class="btn blue">לפרטים ←</span></div></a></div><div class="trust"><div><i>🛡</i><b>שירות מקצועי ואמין</b></div><div><i>🏷</i><b>מחירים הוגנים</b></div><div><i>🛠</i><b>ייעוץ והתקנה</b></div><div><i>✓</i><b>עבודה נקייה</b></div><div><i>⚡</i><b>זמינות מהירה</b></div><div><i>🏢</i><b>פתרונות לעסקים</b></div></div></div></section>'''
(ROOT/'index.html').write_text(page('AGAM | פתרונות חכמים לבית ולעסק',home,'home'),encoding='utf-8')
tech_services=''.join([service('assets/router.jpg','אינטרנט ורשתות','תכנון רשת, Wi‑Fi, Mesh, מגדילי טווח, Access Points ו‑Backhaul קווי.'),service('assets/camera.jpg','מצלמות אבטחה','מצלמות IP/PoE, NVR, צפייה מרחוק ותשתית לבית ולעסק.'),service('assets/cables.jpg','כבלי תקשורת והשחלות','CAT6/CAT6A, נקודות, תעלות, שקעים, השחלות, בדיקות וסימון.'),service('assets/fiber.jpg','סיבים אופטיים','השחלות, הכנות, טיפול בתקלות וחיבור תשתיות סיב.'),service('assets/rack.jpg','ארונות תקשורת','Patch Panels, סוויצ׳ים, תיוג, ניהול כבלים וסידור ארונות.'),service('assets/switch.jpg','טלפוניה ו‑VoIP','חיווט טלפון, נקודות, פקס, מרכזיות ופתרונות VoIP.'),service('assets/lab.jpg','מחשוב ותחנות עבודה','Windows, Office ברישוי תקין, שדרוגים, תחנות עבודה ומחשבים.'),service('assets/lab.jpg','מוסדות וכיתות מחשבים','הקמת כיתות, עמדות תלמידים ומורים, רשת, Wi‑Fi, מצלמות ותחזוקה.')])
tech=f'''<section class="hero tech"><div class="wrap"><div class="hero-copy"><div class="mega division-mega"><img src="assets/agam-mark.png" alt=""><b>AGAM</b> <span>TECH</span></div><h1>אינטרנט, רשתות, תקשורת ומצלמות לבית, לעסק ולמוסדות.</h1><p>תכנון, התקנה ותחזוקה של מערכות תקשורת מתקדמות בהתאמה מדויקת לצורך.</p><div class="cta"><a class="btn blue" href="https://wa.me/{WA}">ליצירת קשר עכשיו</a></div></div></div></section><section class="section soft"><div class="wrap"><div class="section-head"><h2>השירותים שלנו ב‑AGAM TECH</h2><p>פתרונות תקשורת ותשתיות מקצה לקצה.</p></div><div class="service-grid">{tech_services}</div><div class="trust"><div><i>🛡</i><b>שירות מקצועי</b></div><div><i>⚙</i><b>ציוד איכותי</b></div><div><i>⚡</i><b>מענה מהיר</b></div><div><i>🏢</i><b>עסקים ומוסדות</b></div><div><i>🧭</i><b>ייעוץ אישי</b></div><div><i>✓</i><b>עבודה מסודרת</b></div></div></div></section>'''
(ROOT/'tech.html').write_text(page('AGAM TECH | תקשורת ורשתות',tech,'tech'),encoding='utf-8')
gaming_services=''.join([service('assets/gaming.jpg','מחשבי גיימינג בהתאמה אישית','מפרט מותאם למשחקים, למסך ולתקציב עם בדיקות יציבות מלאות.'),service('assets/gaming.jpg','PlayStation / Xbox','קונסולות, חיבור רשת, ציוד היקפי, סטנדים ואביזרים.'),service('assets/gaming.jpg','עמדות גיימינג ועיצוב היקפי','מסכים, מקלדות, עכברים, אוזניות ועמדות מסודרות.'),service('assets/gaming.jpg','סטנדים ואביזרים בהתאמה אישית','סטנדים לבקרים, קונסולות, אוזניות ושמות אישיים.'),service('assets/gaming.jpg','שדרוגי חומרה וביצועים','RAM, SSD, כרטיסי מסך, קירור, תחזוקה ושדרוגים.'),service('assets/gaming.jpg','אביזרים וגאדג׳טים','אוזניות, מיקרופונים, מצלמות, תאורה ואביזרי סטרימינג.'),service('assets/gaming.jpg','מוצרי אקריליק ו‑CNC','שלטים, לוגואים, מעמדים, חלקים ודקורציה בהתאמה אישית.'),service('', 'עיצוב לוגו אישי ב‑CNC עם תאורה','לוגו או שם בחריטה/חיתוך CNC עם תאורת LED לסטודיו, עסק או עמדת גיימינג.',custom=True)])
gaming=f'''<section class="hero gaming"><div class="wrap"><div class="hero-copy"><div class="mega division-mega"><img src="assets/agam-mark.png" alt=""><b>AGAM</b> <span>GAMING & CUSTOM</span></div><h1>מחשבי גיימינג, קונסולות ועיצוב אישי ברמה מקצועית.</h1><p>מחשבים לפי מפרט, PlayStation/Xbox, עמדות גיימינג, פרספקס, CNC, שמות, חתימות ולוגואים מוארים.</p><div class="cta"><a class="btn blue" href="https://wa.me/{WA}">לצפייה במוצרים ושירותים</a></div></div></div></section><section class="section soft"><div class="wrap"><div class="trust"><div><i>🛡</i><b>מוצרים איכותיים</b></div><div><i>👥</i><b>התאמה אישית</b></div><div><i>🚚</i><b>אספקה מהירה</b></div><div><i>🛠</i><b>שדרוג והתקנה</b></div><div><i>💎</i><b>עיצוב פרספקס</b></div><div><i>✨</i><b>לוגו CNC מואר</b></div></div><div class="service-grid" style="margin-top:16px">{gaming_services}</div></div></section>'''
(ROOT/'gaming.html').write_text(page('AGAM GAMING & CUSTOM',gaming,'gaming'),encoding='utf-8')
home_services=''.join([service('assets/home.jpg','תליית טלוויזיות','תלייה מקצועית על קיר, זרוע, סידור כבלים וחיבור רשת/סטרימינג.'),service('assets/home.jpg','התקנת מדפים וזרועות','מדפים, מתקנים, תמונות, אביזרים ופתרונות תלייה.'),service('assets/router.jpg','התקנות בית חכם','טלוויזיות, שואבים, מצלמות, חיישנים, אפליקציות ו‑Wi‑Fi.'),service('assets/home.jpg','מוצרי חשמל','חיבור והתקנה של מוצרים נבחרים; חשמל מבוצע באמצעות חשמלאי מוסמך.'),service('assets/router.jpg','רשת לבית','Mesh, מגדילי טווח, שיפור כיסוי, נקודות רשת וחיבור מכשירים.'),service('assets/camera.jpg','מצלמות לבית','מצלמות אבטחה, צפייה מרחוק, חיבור לרשת והגדרה.'),service('assets/home.jpg','הרכבות והנדימן','הרכבות ריהוט, מתקנים, כוורות, כיסאות ועבודות הנדימן נבחרות.'),service('assets/home.jpg','ברזים ואינסטלציה קלה','החלפת ברזים ועבודות קלות בהתאם לסוג העבודה.')])
homep=f'''<section class="hero home"><div class="wrap"><div class="hero-copy"><div class="mega division-mega"><img src="assets/agam-mark.png" alt=""><b>AGAM</b> <span>HOME</span></div><h1>פתרונות התקנה ושירותים לבית.</h1><p>תליית טלוויזיות, בית חכם, רשת לבית, הנדימן, מוצרים נבחרים, מדפים, ברזים ומצלמות.</p><div class="cta"><a class="btn blue" href="https://wa.me/{WA}">לתיאום שירות לבית</a></div></div></div></section><section class="section soft"><div class="wrap"><div class="section-head"><h2>השירותים שלנו לבית</h2></div><div class="service-grid">{home_services}</div><div class="trust"><div><i>✨</i><b>עבודה נקייה</b></div><div><i>🛠</i><b>שירות מקצועי</b></div><div><i>⚡</i><b>מענה מהיר</b></div><div><i>🏷</i><b>מחירים הוגנים</b></div><div><i>🛡</i><b>אחריות</b></div><div><i>🏠</i><b>פתרונות לבית</b></div></div></div></section>'''
(ROOT/'home.html').write_text(page('AGAM HOME | פתרונות לבית',homep,'house'),encoding='utf-8')
about=f'''<section class="hero about"><div class="wrap"><div class="hero-copy"><div class="mega about-brand">אודות <span><img src="assets/agam-mark.png" alt="">AGAM</span></div><h1>פתרונות חכמים לבית ולעסק — במקום אחד.</h1><p>אנחנו משלבים תקשורת, מחשוב, גיימינג, עיצוב אישי ושירותי בית במבנה ברור: TECH, GAMING & CUSTOM ו‑HOME.</p></div></div></section><section class="section soft"><div class="wrap about-grid"><div class="panel"><h2>למה לבחור בנו?</h2><div class="checks"><div class="check">ניסיון ומקצועיות</div><div class="check">שירות אישי</div><div class="check">עבודה נקייה</div><div class="check">פתרונות מותאמים</div><div class="check">מענה מהיר</div><div class="check">מחירים הוגנים</div></div></div><div class="panel"><h2>שלושה עולמות. צוות אחד.</h2><p>AGAM TECH לתקשורת, רשתות, מצלמות ומחשוב; AGAM GAMING & CUSTOM למחשבי גיימינג, CNC ופרספקס; AGAM HOME להתקנות ושירותים לבית.</p><div class="cta"><a class="btn blue" href="contact.html">דברו איתנו</a></div></div></div></section>'''
(ROOT/'about.html').write_text(page('אודות AGAM',about,'about'),encoding='utf-8')
gallery_items=[('assets/rack.jpg','ארון תקשורת לעסק'),('assets/router.jpg','רשת ו‑Wi‑Fi'),('assets/fiber.jpg','סיבים אופטיים'),('assets/gaming.jpg','עמדת גיימינג'),('assets/home.jpg','תליית טלוויזיה'),('assets/camera.jpg','מצלמות אבטחה'),('assets/lab.jpg','כיתת מחשבים'),('assets/cables.jpg','תשתית תקשורת'),('assets/patch.jpg','Patch Panel'),('assets/switch.jpg','סוויצ׳ים וטלפוניה'),('assets/home.jpg','בית חכם'),('assets/gaming.jpg','עיצוב אישי ו‑CNC')]
gal=''.join(f'<a class="gallery-item" href="contact.html"><img src="{i}" alt="{t}"><b>{t}</b></a>' for i,t in gallery_items)
gallery=f'''<section class="hero gallery"><div class="wrap"><div class="hero-copy"><div class="mega">גלריה</div><h1>פרויקטים, תשתיות ועיצובים.</h1><p>דוגמאות לסוגי העבודות והפתרונות שאנחנו מציעים לבית, לעסק ולמוסדות.</p></div></div></section><section class="section soft"><div class="wrap"><div class="gallery-grid">{gal}</div></div></section>'''
(ROOT/'gallery.html').write_text(page('גלריה | AGAM',gallery,'gallery'),encoding='utf-8')
contact=f'''<section class="hero contact"><div class="wrap"><div class="hero-copy"><div class="mega">צור קשר</div><h1>מוכנים לשדרג את הבית או העסק?</h1><p>השאירו פרטים או שלחו תמונה/סרטון ב‑WhatsApp ונכוון אתכם לשירות המתאים.</p></div></div></section><section class="section soft"><div class="wrap contact-grid"><div class="panel"><h2>שלחו לנו הודעה</h2><form class="form lead-form"><input name="name" placeholder="שם מלא" required><input name="phone" placeholder="טלפון" required><select name="service"><option>בחרו נושא</option><option>AGAM TECH</option><option>GAMING & CUSTOM</option><option>AGAM HOME</option><option>מוסדות וכיתות מחשבים</option></select><input name="area" placeholder="עיר / אזור"><textarea name="message" placeholder="ספרו בקצרה מה צריך לבצע"></textarea><button class="btn blue" type="submit">שליחה ב‑WhatsApp</button></form></div><div class="contact-card"><div class="info"><b>☎ {PHONE}</b><span>שיחה ישירה וייעוץ ראשוני</span></div><div class="info"><b>WhatsApp</b><span>הדרך המהירה לשלוח תמונה או סרטון</span><p><a class="btn blue" href="https://wa.me/{WA}">פתיחת WhatsApp</a></p></div><div class="info"><b>לקוחות פרטיים ועסקיים</b><span>בתים, משרדים, מוסדות וכיתות מחשבים.</span></div></div></div></section>'''
(ROOT/'contact.html').write_text(page('צור קשר | AGAM',contact,'contact'),encoding='utf-8')
print('built',*[p.name for p in ROOT.glob('*.html') if p.name in {'index.html','tech.html','gaming.html','home.html','about.html','gallery.html','contact.html'}])
def relink_cards(file,targets):
    p=ROOT/file; s=p.read_text(encoding='utf-8')
    for t in targets:s=s.replace('<a class="service" href="contact.html">',f'<a class="service" href="{t}">',1)
    p.write_text(s,encoding='utf-8')
def detail(slug,title,subtitle,img,bullets,active='tech'):
    checks=''.join(f'<div class="check">{b}</div>' for b in bullets)
    body=f'''<section class="hero {active if active in {'tech','gaming','home'} else 'tech'}" style="--hero:url('{img}')"><div class="wrap"><div class="hero-copy"><div class="kicker brand-kicker"><img src="assets/agam-mark.png" alt="">AGAM</div><h1>{title}</h1><p>{subtitle}</p><div class="cta"><a class="btn blue" href="https://wa.me/{WA}">קבלת הצעת מחיר</a><a class="btn light" href="contact.html">צור קשר</a></div></div></div></section><section class="section soft"><div class="wrap about-grid"><div class="panel"><h2>מה כולל השירות?</h2><div class="checks">{checks}</div></div><div class="panel"><h2>איך מתחילים?</h2><p>שלחו ב‑WhatsApp תמונה/סרטון, מיקום ותיאור קצר. נבין את הצורך ונכוון אתכם לפתרון המתאים.</p><a class="btn blue" href="https://wa.me/{WA}">שלחו הודעה</a></div></div></section>'''
    (ROOT/slug).write_text(page(f'{title} | AGAM',body,active),encoding='utf-8')
tech_links=['internet.html','cameras.html','cabling.html','fiber.html','racks.html','phone.html','computers.html','education.html']
gaming_links=['gaming-pc.html','consoles.html','gaming-setup.html','stands.html','upgrades.html','accessories.html','cnc-custom.html','cnc-logo.html']
home_links=['tv-install.html','shelves.html','smart-home.html','electrical.html','home-network.html','home-cameras.html','handyman.html','faucets.html']
relink_cards('tech.html',tech_links);relink_cards('gaming.html',gaming_links);relink_cards('home.html',home_links)
details=[
('internet.html','אינטרנט, רשתות ו‑Wi‑Fi','תכנון והקמת רשת יציבה לבית, לעסק ולמוסדות.','assets/router.jpg',['Mesh ומגדילי טווח','Access Points','Backhaul קווי','בדיקות כיסוי ומהירות'],'tech'),
('cameras.html','מצלמות אבטחה','מצלמות IP/PoE, NVR, תשתית וצפייה מרחוק.','assets/camera.jpg',['תכנון מיקום מצלמות','חיווט PoE','NVR והקלטה','צפייה מרחוק מאובטחת'],'tech'),
('cabling.html','כבלי תקשורת והשחלות','CAT6/CAT6A, נקודות רשת, שקעים, תעלות והשחלות.','assets/cables.jpg',['השחלות חדשות','נקודות רשת','סימון ותיוג','בדיקות קישוריות'],'tech'),
('fiber.html','סיבים אופטיים','השחלות סיב, הכנות תשתית וטיפול בתקלות.','assets/fiber.jpg',['תכנון מסלול','השחלת סיב','בדיקת חיבורים','טיפול בתקלות'],'tech'),
('racks.html','ארונות תקשורת','סידור, תיוג ושיקום ארונות תקשורת.','assets/rack.jpg',['Patch Panels','סוויצ׳ים','ניהול כבלים','תיוג ותיעוד'],'tech'),
('phone.html','טלפוניה ו‑VoIP','חיווט טלפון, נקודות, פקס ופתרונות VoIP.','assets/switch.jpg',['חיווט קווי','נקודות טלפון','VoIP ומרכזיות','פקס ושילוב ברשת'],'tech'),
('computers.html','מחשוב ותחנות עבודה','מחשבים, Windows, Office ברישוי תקין ושדרוגים.','assets/lab.jpg',['מחשבי משרד','SSD/RAM','Windows ודרייברים','Office ותוכנות'],'tech'),
('education.html','מוסדות וכיתות מחשבים','תשתיות, רשת, מחשבים ומצלמות לבתי ספר ומוסדות.','assets/lab.jpg',['כיתות מחשבים','Wi‑Fi מוסדי','ארונות תקשורת','תחזוקה שוטפת'],'tech'),
('gaming-pc.html','מחשבי גיימינג בהתאמה אישית','מפרט לפי משחקים, מסך ותקציב.','assets/gaming.jpg',['CPU/GPU מותאם','קירור וספק','בדיקות יציבות','סט מחשב מלא'],'gaming'),
('consoles.html','PlayStation / Xbox','חיבור קונסולות, רשת, אביזרים וסטנדים.','assets/gaming.jpg',['רשת קווית/אלחוטית','שיפור latency','אביזרים','סטנדים אישיים'],'gaming'),
('gaming-setup.html','עמדות גיימינג','תכנון עמדת גיימינג נקייה ומרשימה.','assets/gaming.jpg',['מסכים','תאורה','סידור כבלים','ציוד היקפי'],'gaming'),
('stands.html','סטנדים ואביזרים אישיים','סטנדים לבקרים, אוזניות וקונסולות בפרספקס.','assets/gaming.jpg',['שם אישי','חתימה','Gamer Tag','תאורת LED'],'gaming'),
('upgrades.html','שדרוגי חומרה וביצועים','שדרוג מחשב קיים בצורה נכונה.','assets/gaming.jpg',['RAM','SSD','כרטיס מסך','קירור ותחזוקה'],'gaming'),
('accessories.html','אביזרים וגאדג׳טים','ציוד היקפי לגיימינג וסטרימינג.','assets/gaming.jpg',['אוזניות','מיקרופונים','מצלמות','תאורה'],'gaming'),
('cnc-custom.html','עיצוב פרספקס ו‑CNC','חיתוך, חריטה וייצור אלמנטים אישיים.','assets/gaming.jpg',['פאנלים','שמות וחתימות','לוגואים','תושבות וסטנדים'],'gaming'),
('cnc-logo.html','לוגו אישי ב‑CNC עם תאורה','עיצוב וייצור לוגו/שם אישי מפרספקס עם תאורת LED.','assets/gaming.jpg',['חיתוך CNC','חריטה','תאורת LED','עיצוב לפי לוגו/שם'],'gaming'),
('tv-install.html','תליית טלוויזיות','תלייה מקצועית, זרועות וסידור חיבורים.','assets/home.jpg',['בחירת גובה','זרוע מתאימה','סידור כבלים','חיבור סטרימינג'],'home'),
('shelves.html','מדפים וזרועות','התקנת מדפים, מתקנים ואביזרים.','assets/home.jpg',['מדפים','זרועות','תמונות','מתקנים'],'home'),
('smart-home.html','בית חכם','חיבור והגדרת ציוד חכם ואפליקציות.','assets/router.jpg',['Smart TV','שואבים','חיישנים','אפליקציות'],'home'),
('electrical.html','מוצרי חשמל','התקנות נבחרות; עבודות חשמל באמצעות חשמלאי מוסמך.','assets/home.jpg',['הכנות נלוות','חיבור ציוד','בדיקות','חשמלאי מוסמך כשנדרש'],'home'),
('home-network.html','רשת לבית','שיפור Wi‑Fi, Mesh ונקודות רשת.','assets/router.jpg',['Mesh','מגדילי טווח','נקודות רשת','שיפור קליטה'],'home'),
('home-cameras.html','מצלמות לבית','מצלמות אבטחה וחיבור לצפייה מרחוק.','assets/camera.jpg',['מצלמות IP','חיבור לרשת','הקלטה','צפייה מרחוק'],'home'),
('handyman.html','הנדימן והרכבות','הרכבות והתקנות קטנות לבית ולעסק.','assets/home.jpg',['ריהוט','מתקנים','כוורות','הרכבות נבחרות'],'home'),
('faucets.html','ברזים ואינסטלציה קלה','החלפת ברזים ועבודות קלות בהתאם לצורך.','assets/home.jpg',['החלפת ברז','חיבור אביזרים','בדיקת נזילות','גימור נקי'],'home')]
for d in details:detail(*d)
print('detail pages',len(details))
